# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "avatarUrl": "torrance.png",
  "name": "Jack",
  "isPro": "",
  "password": "shining"
}

###

## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "torans@overlook.net",
  "password": "shining"
}

###

## Отправить изображение

POST http://localhost:5000/users/67cdac083c2ccdd9b1f53752/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="logo-background-2.jpg"
Content-Type: image/jpeg

< C:\Users\Пользователь\Downloads/logo-background-2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

##
